apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datadog-secret-reader
  namespace: datadog-helm
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["dd-helm-test"]  # Update if your secret has a different name
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datadog-read-secrets
  namespace: datadog-helm
subjects:
  - kind: ServiceAccount
    name: datadog-agent
    apiGroup: ""
    namespace: datadog-helm  # Change to the correct namespace for your SA
roleRef:
  kind: Role
  name: datadog-secret-reader
  apiGroup: ""
